default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5

development:
  <<: *default
  host: localhost
  database: study_app
  username: devuser
  password: devuser

test:
  <<: *default
  database: study_app_test